server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/swiggy
    username: postgres
    password: password
  datasource:
    initialization-mode: always

jwt:
  secret: your_jwt_secret
